name: Cross-Platform Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest  
            platform: windows
          - os: macos-latest
            platform: macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Verify Bun installation
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript type checking
        run: bun run typecheck

      - name: Run unit tests
        run: bun test tests/unit/ --timeout 30000
        env:
          NODE_ENV: test
          CI: true

      - name: Run integration tests
        run: bun test tests/integration/ --timeout 60000
        env:
          NODE_ENV: test
          CI: true

      - name: Run cross-platform tests
        run: bun test tests/platform/ --timeout 30000
        env:
          NODE_ENV: test
          CI: true

      - name: Run format conversion tests
        run: bun test tests/conversion/ --timeout 30000
        env:
          NODE_ENV: test
          CI: true

      - name: Test CLI installation
        run: |
          bun run install
          codeflow --version
        shell: bash

      - name: Test project setup (dry run)
        run: codeflow setup . --type opencode --dry-run
        shell: bash

      - name: Test agent format conversion (dry run)
        run: codeflow convert-all --dry-run
        shell: bash

      - name: Test MCP server configuration (dry run)
        run: codeflow mcp list
        shell: bash

  test-coverage:
    name: Test Coverage Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests with coverage
        run: bun test --coverage --coverage-reporter=lcov
        env:
          NODE_ENV: test
          CI: true

      # Note: Coverage reporting can be extended with services like Codecov if needed
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage/lcov.info

  test-real-agents:
    name: Validate Real Agents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Validate base agents
        run: |
          echo "Testing base agents parsing..."
          echo "Found $(find agent/ -name "*.md" -not -name "README*" | wc -l) agent files"
          # Run the validation test once - it validates all agents internally
          bun test -t "validates all existing agents" --timeout 15000

      - name: Validate OpenCode agents
        run: |
          echo "Testing OpenCode agents parsing..."
          echo "Found $(find opencode-agents/ -name "*.md" -not -name "README*" | wc -l) opencode agent files"
          # Just list them as validation happens in the main test
          find opencode-agents/ -name "*.md" -not -name "README*" | head -5 | while read file; do
            echo "Found: $file"
          done

      - name: Test format conversions
        run: |
          echo "Testing format conversion accuracy..."
          bun run typecheck
          mkdir -p /tmp/test-conversion
          codeflow convert ./agent /tmp/test-conversion claude-code --dry-run

  test-mcp-integration:
    name: MCP Server Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test MCP server startup
        run: |
          # Test that MCP server can start and initialize properly
          # We'll test with a short-lived process since MCP servers are stdio-based
          echo "Testing MCP server initialization..."
          
          # Create temp directory cross-platform
          if [ "$RUNNER_OS" = "Windows" ]; then
            TEMP_DIR="$RUNNER_TEMP"
          else
            TEMP_DIR="/tmp"
          fi
          
          # Cross-platform timeout implementation
          if command -v timeout >/dev/null 2>&1; then
            TIMEOUT_CMD="timeout 10s"
          elif command -v gtimeout >/dev/null 2>&1; then
            TIMEOUT_CMD="gtimeout 10s"
          else
            # Fallback for systems without timeout
            TIMEOUT_CMD=""
          fi
          
          # Use MCP integration test instead of manual process management
          echo "Testing MCP server via integration tests..."
          bun test tests/integration/mcp-server.test.ts -t "MCP server starts and responds to ping" --timeout 15000
          
          if [ $? -eq 0 ]; then
            echo "✅ MCP server integration test passed"
          else
            echo "❌ MCP server integration test failed"
            exit 1
          fi

      - name: Test MCP tool registration
        run: |
          echo "Testing MCP tool registration..."
          # This runs the integration tests specifically for MCP
          bun test tests/integration/mcp-server.test.ts --timeout 45000

  test-file-operations:
    name: File System Operations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test file system operations
        run: |
          # Test file creation, reading, and deletion
          mkdir -p test-workspace
          echo "test content" > test-workspace/test.txt
          
          # Test CLI can handle workspace
          codeflow status test-workspace || echo "Expected: no .opencode directory"
          
          # Clean up using cross-platform approach
          if [ "$RUNNER_OS" = "Windows" ]; then
            if command -v powershell >/dev/null 2>&1; then
              powershell -Command "Remove-Item -Recurse -Force test-workspace -ErrorAction SilentlyContinue"
            else
              rm -rf test-workspace 2>/dev/null || true
            fi
          else
            rm -rf test-workspace
          fi
        shell: bash

      - name: Test Unicode file handling
        run: |
          # Test with Unicode file names and content (only on Unix-like systems)
          if [ "$RUNNER_OS" != "Windows" ]; then
            mkdir -p unicode-test
            echo "Unicode content: 你好世界 🌍" > "unicode-test/测试文件.txt"
            ls -la unicode-test/
            rm -rf unicode-test
          else
            echo "Skipping Unicode file test on Windows (filesystem limitations)"
            # Test simpler Unicode content on Windows
            mkdir -p unicode-test
            echo "Unicode content: Hello World" > unicode-test/test-file.txt
            ls -la unicode-test/
            if command -v powershell >/dev/null 2>&1; then
              powershell -Command "Remove-Item -Recurse -Force unicode-test -ErrorAction SilentlyContinue"
            else
              rm -rf unicode-test 2>/dev/null || true
            fi
          fi
        shell: bash

      - name: Test path resolution
        run: bun test tests/platform/cross-platform.test.ts -t "Platform-Specific Path Resolution" --timeout 15000

  report-results:
    name: Test Results Summary
    runs-on: ubuntu-latest
    needs: [test, test-coverage, test-real-agents, test-mcp-integration, test-file-operations]
    if: always()

    steps:
      - name: Test Results
        run: |
          echo "## Cross-Platform Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.test.result }}" = "success" ]; then
            echo "✅ Core tests passed on all platforms" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Core tests failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-coverage.result }}" = "success" ]; then
            echo "✅ Coverage tests completed" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Coverage tests had issues" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-real-agents.result }}" = "success" ]; then
            echo "✅ Real agent validation passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Real agent validation failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-mcp-integration.result }}" = "success" ]; then
            echo "✅ MCP server integration tests passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ MCP server integration tests failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-file-operations.result }}" = "success" ]; then
            echo "✅ File system operations tests passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ File system operations tests failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Total test suites:** 5" >> $GITHUB_STEP_SUMMARY
          echo "**Platform coverage:** Linux, Windows, macOS" >> $GITHUB_STEP_SUMMARY
          echo "**Test categories:** Unit, Integration, Cross-platform, Format conversion, Real agents" >> $GITHUB_STEP_SUMMARY